# Generated by Django 3.0.3 on 2021-04-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rating', models.IntegerField(choices=[(1, '1-Very Bad'), (2, '2-Bad'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Excellent')])),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogportal.Post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
